[package]
name = "horizon"
version = "0.0.1"
description = "The universal music app."
authors = ["tygerxqt", "NyanSpaghetti"]
license = "GPL-3.0-only"
repository = "https://github.com/lofustudio/horizon"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.5", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha.0", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rodio = "0.17.1"

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "horizonlib"
crate-type = ["staticlib", "cdylib", "rlib"]
