[package]
name = "horizon"
version = "0.0.1"
description = "A stupidly simple music app."
authors = ["tygerxqt", "NyanSpaghetti"]
license = "GPL-3.0-only"
repository = "https://github.com/lofustudio/horizon"
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.0.0-alpha.4", features = [] }
tauri-utils = "=2.0.0-alpha.4"

[dependencies]
tauri = { version = "2.0.0-alpha.0", features = ["path-all", "shell-open", "window-close", "window-hide", "window-maximize", "window-minimize", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rodio = "0.17.1"

[features]
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "horizonlib"
crate-type = ["staticlib", "cdylib", "rlib"]
