name: 'setup deps'
description: 'Set up dependencies required to build'
inputs:
  ios:
    description: 'Prepare dependencies for iOS builds'
    required: false
    default: '0'
  android:
    description: 'Prepare dependencies for Android builds'
    required: false
    default: '0'
outputs:
  ndk-path:
    description: 'NDK_HOME'
    value: ${{ steps.setup-ndk.outputs.ndk-path }}

runs:
  using: composite
  steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: install dependencies (ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl3 libasound2-dev

    - name: install frontend dependencies
      shell: bash
      run: yarn install

    - name: install tauri-cli android-fix branch (android)
      if: inputs.android == '1'
      shell: bash
      run: |
        cargo install tauri-cli --git https://github.com/simonhyll/tauri --branch android-fix
        sed -i -e 's/"tauri": "tauri"/"tauri": "cargo-tauri"/g' ./package.json

    - name: setup Java (android)
      uses: actions/setup-java@v3
      if: inputs.android == '1'
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: setup NDK (android)
      if: inputs.android == '1'
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: false

    - name: initalize AStudio Project (android)
      if: inputs.android == '1'
      shell: bash
      run: yarn tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: initalize Xcode Project (ios)
      if: inputs.ios == '1'
      shell: bash
      run: yarn tauri ios init
      env:
        TAURI_APPLE_DEVELOPMENT_TEAM: 'PIPPAGAY'
        HOMEBREW_NO_INSTALL_CLEANUP: 'TRUE'

    - name: install Apple certificates (ios)
      uses: Apple-Actions/import-codesign-certs@v2
      if: inputs.ios == '1'
      with:
        p12-file-base64: ${{ inputs.certificate }}
        p12-password: ${{ inputs.certificate_password }}

    - name: install provisioning profile (ios)
      if: inputs.ios == '1'
      shell: bash
      env:
        BUILD_PROVISION_PROFILE_BASE64: ${{ inputs.profile }}
      run: |
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
