name: 'release'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag assets will be uploaded to'
        required: true
        type: string

jobs:
  release-os:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/deps

      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.tag }} ./src-tauri/target/release/bundle/**/* --clobber

  release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps
        id: 'deps'
        with:
          android: '1'

      - name: build
        run: yarn tauri android build
        env:
          NDK_HOME: ${{ steps.deps.outputs.ndk-path }}

      - name: upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ inputs.tag }} ./src-tauri/gen/android/app/build/outputs/apk/**/**/*.apk --clobber

  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: ./.github/actions/deps
  #       with:
  #         ios: '1'

  #     - name: build (ios)
  #       run: yarn tauri ios build
  #       env:
  #         TAURI_APPLE_DEVELOPMENT_TEAM: "PIPPAGAY"
