name: 'release'
on:
  push:
    branches:
      - 'stable'
  workflow_dispatch:

jobs:
  release-os:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/deps

      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Horizon v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false

  release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps
        id: 'deps'
        with:
          android: '1'

      - name: build
        run: yarn tauri android build
        env:
          NDK_HOME: ${{ steps.deps.outputs.ndk-path }}

      - name: upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          gh release upload v${{ env.PACKAGE_VERSION }} ./src-tauri/gen/android/app/build/outputs/apk/**/**/*.apk

  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: ./.github/actions/deps
  #       with:
  #         ios: '1'

  #     - name: build (ios)
  #       run: yarn tauri ios build
  #       env:
  #         TAURI_APPLE_DEVELOPMENT_TEAM: "PIPPAGAY"
