name: 'test'
on:
  push:
    branches:
      - '**'
      - '!stable'
  pull_request:
    branches:
      - 'stable'
  workflow_dispatch:

jobs:
  build-os:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps

      - name: build (${{ matrix.platform }})
        id: build_os
        uses: tauri-apps/tauri-action@v0
        with:
          includeDebug: true
          includeRelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload ${{ matrix.platform }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: "${{ join(fromJSON(steps.build_os.outputs.artifactPaths), '\n') }}"
          if-no-files-found: ignore

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps
        id: 'deps'
        with:
          android: '1'

      - name: build (android)
        run: yarn tauri android build --debug --split-per-abi
        env:
          NDK_HOME: ${{ steps.deps.outputs.ndk-path }}

      - name: upload (android)
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            src-tauri/gen/android/horizon/app/build/outputs/apk/**/**/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps
        with:
          ios: '1'

      - name: build (ios)
        run: yarn tauri ios build --debug
        env:
          TAURI_APPLE_DEVELOPMENT_TEAM: "PIPPAGAY"